### PR TITLE
RetroPie Block

### PR DESCRIPTION
**Pull request by RetroPieNerd**
Here is a block that allows you to install the RetroPie-Setup script and boot to it.

### CODE REVIEW

**Comment by lurch** [comment]
Why does it download it into `/boot` ? (which is typically quite small)
Wouldn't it be better to just download it to `/home/pi` ?

**Comment by davidferguson** [comment]
I agree - it would be better to download it into the rootfs rather than the boot partition, for space reasons but also because I'd rather blocks didn't modify the contents of /boot/PiBakery/

**Comment by RetroPieNerd** [comment]
I will fix in a new pull request.

**Comment by RetroPieNerd** [comment]
Some times I am so dumb! XD

**Pull request closed without merging**
